<<<<<<< HEAD
<<<<<<< HEAD
theme: jekyll-theme-slate
remote_theme: thmpltfrmwrk
=======
theme: jekyll-theme-slate
>>>>>>> parent of 4ad5797... Merge pull request #1 from bsocially/bsocially-patch-1
=======
theme: jekyll-theme-slate
theme: thmpltfrmwrk
>>>>>>> parent of 9119606... combine
